apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: MTIz # base64 of "123"
  POSTGRES_USER: cG9zdGdyZXM= # base64 of "postgres"
  POSTGRES_DB: dG9fZG9fbGlzdF9kZXZlbG9wbWVudA== # base64 of "to_do_list_development"

