apiVersion: v1
kind: Secret
metadata:
  name: rails-secret
type: Opaque
data:
  DB_HOST: cG9zdGdyZXMtZGI=           # "postgres-db"
  DB_PORT: NTQzMg==                  # "5432"
  DB_USERNAME: cG9zdGdyZXM=          # "postgres"
  DB_PASSWORD: MTIz                  # "123"
  DB_NAME: dG9fZG9fbGlzdF9kZXZlbG9wbWVudA== # "to_do_list_development"

